cmd/nhctl/cmds/init.go, deployments/chart/Chart.yaml, internal/nhctl/app/application_config.go
* fix init clone nocalhost git to https
* change bookinfo repo to https
* init username and password
* chart mariadb change to coding
=> fix(nhctl): fix init something

deployments/chart/values.yaml
fix(nhctl): mariadb docker image change to docker image
=> fix(nhctl): mariadb docker image change to docker image

cmd/nhctl/cmds/init.go, internal/nhctl/app/application_config.go, internal/nhctl/request/request.go
add bookinfo from coding git repo
=> feat(nhctl): add init bookinfo coding source

cmd/nhctl/cmds/dev_start.go, cmd/nhctl/cmds/root.go, cmd/nhctl/test/nocalhost/config.yaml, cmd/nhctl/test/nocalhost/test_manifest.sh, internal/nhctl/app/application.go, pkg/nhctl/log/log.go
wait for containers to be running when `dev start`
=> feat(nhctl): wait for container to be running when `dev start`

cmd/nhctl/cmds/init.go, internal/nhctl/app/application_config.go, internal/nhctl/request/request.go, pkg/nhctl/clientgoutils/clientgo_utils.go
* add init --force params
* fixed minikube port: 31219, it means 2020/12/19 will be public 😁
=> feat(nhctl): repeat init --force and fixed minikube port

cmd/nhctl/cmds/init.go
feat(nhctl): fix force command
=> feat(nhctl): fix force command

cmd/nhctl/cmds/init.go, internal/nhctl/app/application_config.go, pkg/nhctl/clientgoutils/clientgo_utils.go
* add init rules
* add flush old data timeout, only --force flag
=> feat(nhctl): add init rlues, add delete namespace time

cmd/nhctl/cmds/file_sync.go
feat(nhctl): fix sync double comment
=> feat(nhctl): fix sync double comment

internal/nocalhost-api/model/user_base.go, internal/nocalhost-api/repository/user/user_base_repo.go, internal/nocalhost-api/service/user/user_service.go, pkg/nocalhost-api/app/api/v1/user/create.go, pkg/nocalhost-api/app/api/v1/user/login.go, pkg/nocalhost-api/app/api/v1/user/update.go, pkg/nocalhost-api/app/api/v1/user/user.go
references: nocalhost/nocalhost-web#1
=> feat(api): user set admin

internal/nhctl/app/application.go, internal/nhctl/app/dev_end.go
=> feat(nhctl): syncthing bug

cmd/nhctl/cmds/dev_start.go, cmd/nhctl/cmds/file_sync.go, internal/nhctl/app/application.go, internal/nhctl/app/application_config.go, internal/nhctl/app/options.go, internal/nhctl/app/svc_profile.go, internal/nhctl/app/syncthing.go, internal/nhctl/syncthing/install.go, internal/nhctl/syncthing/install_test.go, internal/nhctl/syncthing/local/syncthingTeamplates.go, internal/nhctl/syncthing/syncthing.go
Reverts nocalhost/nocalhost#42
=> Revert "Revert "feat(nhctl): generate and specify ignorefile before synchronizing""

internal/nocalhost-dep/webhook/webhook.go
feat(nocalhost-dep): fix mutiple pods dependent but wait first bug
=> feat(nocalhost-dep): fix mutiple pods dependent but wait first bug

deployments/chart/values.yaml
feat(nocalhost-api): add deployment resource request
=> feat(nocalhost-api): add deployment resource request

cmd/nhctl/cmds/init.go, cmd/nhctl/cmds/version.go, internal/nhctl/app/application_config.go, scripts/build/nhctl/.variables
feat(nhctl): nhctl init version component
=> feat(nhctl): nhctl init version component

cmd/nhctl/cmds/init.go
feat(nhctl): add init version support
=> feat(nhctl): add init version support

.github/workflows/api-docker.yml, .github/workflows/dep-docker.yml, .github/workflows/nhctl.yml
=> merge github action

.github/workflows/api-docker.yml
=> modified ci actions

deployments/chart/templates/configmap.yaml, internal/nhctl/request/request.go
feat(nhctl): release mode and fix init add user
=> feat(nhctl): release mode and fix init add user

deployments/chart/values.yaml
feat(nocalhost-api): fix mariadb eks
=> feat(nocalhost-api): fix mariadb eks

internal/nhctl/app/svc_profile.go
feat(nhctl): fix syncFilePattern
=> feat(nhctl): fix syncFilePattern

internal/nhctl/app/application_config.go
=> feat(nhctl): fix HEAD

cmd/nhctl/cmds/file_sync.go, internal/nhctl/app/application.go, internal/nhctl/app/application_config.go
=> Try fix syncthing

cmd/nhctl/cmds/tpl/tpl.go
feat(nhctl): tpl new paramaters
=> feat(nhctl): tpl new paramaters

.github/ISSUE_TEMPLATE/bug-report.md, .github/ISSUE_TEMPLATE/enhancement.md, .github/ISSUE_TEMPLATE/support.md
=> merge from main

.github/workflows/dep-installer-job-docker.yml, deployments/chart/values.yaml
=> Reduce resource

cmd/nhctl/cmds/init.go, pkg/nhctl/clientgoutils/clientgo_utils.go
=> Minikube init mariadb pvc

.github/workflows/release.yml
feat(nocalhost-dep): fix env version
=> feat(nocalhost-dep): fix env version

.github/workflows/release.yml, pkg/nocalhost-api/app/api/v1/applications/update.go
=> release 0.2.3

cmd/nhctl/cmds/port_forward.go
feat(nocalhost-dep): fix port-forward
=> feat(nocalhost-dep): fix port-forward

internal/nocalhost-api/repository/application/application_repo.go, internal/nocalhost-api/repository/user/user_base_repo.go, pkg/nocalhost-api/app/api/v1/user/update.go, pkg/nocalhost-api/app/api/v1/user/user.go
Fix(api): Fix bugs in user modification function
=> Fix(api): Fix bugs in user modification function

cmd/nhctl/cmds/config_edit.go, internal/nhctl/app/application.go
fix(nhctl): fix config edit err
=> fix(nhctl): fix config edit err

pkg/nocalhost-api/app/api/v1/cluster/delete.go
Fix the error of deleting the no longer existing kubernetes cluster
=> feat(api): Fix the error when deleting cluster

.github/workflows/release.yml, internal/nhctl/syncthing/daemon/daemon.go, vendor/modules.txt
=> release v0.2.7

deployments/nocalhost-api/Dockerfile
feat(nocalhost-api): fix Shanghai  time
=> feat(nocalhost-api): fix time

deployments/dep-install-job/webhook/mutating-webhook.yaml, internal/nhctl/app/enum.go
=> Support statefulset

cmd/nhctl/cmds/cmdutil.go, cmd/nhctl/cmds/port_forward_start.go, cmd/nhctl/cmds/root.go, internal/nhctl/app/application.go, pkg/nhctl/clientgoutils/clientgo_utils.go
feat(nhctl): support statefulset port-forward
=> feat(nhctl): support statefulset port-forward

README.md, README_ZH.md
=> doc: Add hiring

cmd/nhctl/cmds/describe.go, cmd/nhctl/cmds/dev_start.go, cmd/nhctl/cmds/port_forward_end.go
support statefulset port-forward list and end
=> feat(nhctl): support statefulset port-forward list and end

internal/nocalhost-dep/webhook/webhook.go
ignore recreate resource with annotations
=> feat(nocalhost-dep): add ignore annotations

cmd/nhctl/cmds/install.go
feat(nhctl): support helmValue in config
=> feat(nhctl): support helmValue in config

internal/nhctl/app/application.go, internal/nhctl/app/getter.go, internal/nhctl/app/install.go, internal/nhctl/app/uninstall.go, internal/nhctl/utils/util.go
feat(nhctl): support kustomize
=> feat(nhctl): support kustomize

cmd/nhctl/cmds/apply.go, internal/nhctl/app/install.go, internal/nhctl/app/upgrade.go, pkg/nhctl/clientgoutils/apply.go, pkg/nhctl/clientgoutils/resource_create.go
feat(nhctl): support kustomize apply
=> feat(nhctl): support kustomize apply

cmd/nhctl/cmds/dev_start.go, cmd/nhctl/cmds/dev_terminal.go, internal/nhctl/app/exec.go
feat(nhctl): dev terminal support specify pod
=> feat(nhctl): dev terminal support specify pod

internal/nocalhost-api/model/cluster_user.go, internal/nocalhost-api/repository/cluster_user/cluster_user_repo.go, internal/nocalhost-api/service/cluster_user/cluster_user_service.go, pkg/nocalhost-api/app/api/v1/cluster_user/get.go, pkg/nocalhost-api/app/router/api.go
Adding DevStartAppendCommand、StorageClass to devSpace list
=> feat(api): dev space adaption v2

cmd/nhctl/cmds/dev_end.go, cmd/nhctl/cmds/reset.go, cmd/nhctl/cmds/sync.go, cmd/nhctl/cmds/uninstall.go, internal/nhctl/app/dev_end.go, internal/nhctl/app/options.go
=> feat(nhctl): resume file sync

internal/nhctl/app/upgrade.go
feat(nhctl): helm upgrade dep build
=> feat(nhctl): helm upgrade dep build

pkg/nocalhost-api/app/api/v1/applications/application.go
feat(nocalhost-api): support kustomize type
=> feat(nocalhost-api): support kustomize type

cmd/nhctl/cmds/init_demo.go, internal/nhctl/app/const.go, internal/nhctl/profile/config_v2.go, internal/nhctl/request/request.go
feat(nhctl): fix RemoteDebugPort
=> feat(nhctl): fix RemoteDebugPort

.github/workflows/test.yml
=> add workflow test

.github/workflows/test.yml
=> update workflow test

.github/workflows/test.yml
=> reindent code

.github/workflows/test.yml
=> indent code

.github/workflows/test.yml
=> add more log

.github/workflows/test.yml
=> add timeout

.github/workflows/testcase.yml
=> fix image name issue

.github/workflows/testcase.yml
Co-authored-by: p_caiwfeng <p_caiwfeng@tencent.com>
=> fix image name issue (#389)

deployments/dep-install-job/Dockerfile, deployments/dep-install-job/installer.sh, scripts/build/nhctl/.variables, test/main.go, test/util/util.go
try to fix branch name not correct issue
=> fix branch issue

cmd/nhctl/cmds/init_demo.go, internal/nhctl/request/request.go, pkg/nhctl/tools/helper.go
=> feat(nhctl): nhctl init demo fix output

.github/workflows/test.yml
use kubernetes in docker to run test parallelly
=> parallel test

cmd/nhctl/cmds/init_demo.go, internal/nhctl/app/git.go, internal/nhctl/app/install.go, internal/nhctl/app/upgrade.go, internal/nhctl/appmeta/application_meta.go, internal/nhctl/port-forward/port_status_default.go, internal/nhctl/port-forward/port_status_windows.go, internal/nhctl/request/request.go, internal/nhctl/utils/util.go, pkg/nhctl/tools/helper.go, pkg/nhctl/tools/helper_test.go
=> ignore warn

deployments/testcase/Dockerfile
hotfix: fix apt install cannot found package issue
=> using binary install instead of apt install

.github/workflows/release.yml, pkg/nocalhost-api/app/api/v1/cluster_user/dev_space.go
- fix dev space resource quota can not updated
- disable plugin release
=> feat(nocalhost):  hotfix for v0.4.1-rc3

internal/nhctl/app/install.go, internal/nhctl/app/upgrade.go, internal/nhctl/appmeta/application_meta.go
- fix bug cause long time block
- fix helm do not record release name
=> fix(nhctl): fix some bug

CHANGELOG/CHANGELOG-v0.4.6.md
=> Add 0.4.6 changelogs

CHANGELOG/CHANGELOG-v0.4.5.md, README.md, README_ZH.md
Fix the wrong message display in WeChat group image
=> Fix wechat group image 

cmd/nhctl/cmds/install.go, internal/nhctl/app/application.go, internal/nhctl/app/getter.go, internal/nhctl/app/install.go, internal/nhctl/app/upgrade.go, internal/nhctl/appmeta/application_meta.go, internal/nocalhost-api/model/application_model.go, pkg/nocalhost-api/app/api/v1/applications/application.go, pkg/nocalhost-api/app/api/v1/applications/get.go
feat(nhctl): use same application type
=> feat(nhctl): use same application type

internal/nocalhost-dep/webhook/webhook.go
Signed-off-by: mouuii <zhouchengbin@koderover.com>
=> fix word spelling

internal/nhctl/appmeta_manager/application_secret_boss.go, internal/nhctl/appmeta_manager/helmUtil.go
daemon will delete secret automatictly if helm install too slow
=> feat(nhctl): fix nhctl helm install

cmd/nhctl/cmds/dev_associate.go, cmd/nhctl/cmds/dev_associate_queryer.go, cmd/nhctl/cmds/init_demo.go, cmd/nhctl/cmds/server_upgrade_test.go, cmd/nhctl/cmds/sync_status.go, internal/nhctl/app/application.go, internal/nhctl/dev_dir/dev_dir_mapping.go, internal/nhctl/dev_dir/dev_dir_mapping_db.go
- remove adaption for appmeta
- hide svc pack when svc both having container pack and without container pack
- un check svc while de-asscociate
=> feat(nhctl): adaption for associate

cmd/nhctl/cmds/dev_start.go, internal/nhctl/controller/cronjob_controller.go, internal/nhctl/controller/daemonset_controller.go, internal/nhctl/controller/deployment_controller.go, internal/nhctl/controller/dev_start.go, internal/nhctl/controller/job_controller.go, internal/nhctl/controller/raw_controller.go, internal/nhctl/controller/syncthing.go, internal/nhctl/model/model.go
=> feat(nhctl): supports specify image

deployments/nocalhost-api/Dockerfile, scripts/build/api/build
Signed-off-by: Yu Yicai <yuyicai@hotmail.com>
=> change base image to alpine

internal/nocalhost-api/sleep/asleep.go, internal/nocalhost-api/sleep/inspect.go, internal/nocalhost-api/sleep/job.go, internal/nocalhost-api/sleep/wakeup.go, pkg/nocalhost-api/app/api/v1/cluster_user/sleep.go
Signed-off-by: Weijie <raoh.wu@gmail.com>
=> - bugfix for sleep

internal/nocalhost-api/sleep/asleep.go, internal/nocalhost-api/sleep/vcluster.go, internal/nocalhost-api/sleep/wakeup.go
Signed-off-by: Weijie <raoh.wu@gmail.com>
=> - misc: sleep & vcluster

pkg/nocalhost-api/app/api/v1/service_account/service_account.go
Signed-off-by: yuyicai <yuyicai@hotmail.com>
=> fix(api): override with host kubeconfig cluster

internal/nhctl/dev_dir/dev_dir_mapping.go
Signed-off-by: p_caiwfeng <p_caiwfeng@tencent.com>
=> hotfix(nhctl): associate queryer npe

internal/nhctl/syncthing/daemon/daemon.go
=> fix zombie process

README.md, cmd/nhctl/cmds/root.go, cmd/nhctl/cmds/vpn_connect.go, cmd/nhctl/cmds/vpn_elevate.go, cmd/nhctl/cmds/vpn_reconnect.go, internal/nhctl/daemon_client/client.go, internal/nhctl/daemon_common/daemon.go, internal/nhctl/daemon_server/daemon.go, internal/nhctl/utils/util.go, internal/nhctl/vpn/util/elevatecheck_others.go
Reverts nocalhost/nocalhost#1257
=> Revert "Fix sudo daemon err"

pkg/nocalhost-api/pkg/clientgo/secret.go
at secret.go file, DeleteSecret method is delete but used update api actually .
=> fix: DeleteSecret method is delete but used update api actually

deployments/chart/templates/_helpers.tpl, deployments/chart/templates/ingress.yaml, deployments/chart/values.yaml
how to use:
`helm install nocalhost nocalhost/nocalhost -n nocalhost --create-namespace --set ingress.hosts={nocalhost.domain.com} --set ingress.enabled=true`
Signed-off-by: Yicai Yu <yuyicai@hotmail.com>
=> feat(api): add ingress

internal/nocalhost-api/model/cluster_model.go, internal/nocalhost-api/repository/cluster/cluster_repo.go, internal/nocalhost-api/service/cluster/cluster_service.go, pkg/nocalhost-api/app/api/v1/cluster/cluster.go, pkg/nocalhost-api/app/api/v1/cluster/create.go, pkg/nocalhost-api/app/api/v1/service_account/service_account.go
Signed-off-by: Yicai Yu <yuyicai@hotmail.com>
close #1317
=> feat(api): add extra api server

internal/nhctl/nocalhost/svc_type.go
closes https://github.com/nocalhost/nocalhost/issues/1342
Signed-off-by: MingkeVan [comeandgo@2014@gmail.com](mailto:comeandgo2014@gmail.com)
=> fix(nhctl):  add support for deprecated deployments and statefulsets api

internal/nocalhost-api/global/static.go, pkg/nocalhost-api/app/api/v1/service_account/service_account.go, pkg/nocalhost-api/pkg/clientgo/client.go
Signed-off-by: Yicai Yu <yuyicai@hotmail.com>
fix: #1327 
=> fix(api): gen sa secret token

internal/nhctl/const/const.go, internal/nhctl/controller/dev_start.go
=> fix sidecar sshd failed

internal/nhctl/vpn/pkg/connect.go
=> fix: get cidr without hostNetwork

README.md
Add sponsor section in README. Maintaining open source projects is hard. We would like to appreciate existing sponsors and encourage more sponsors.
=> doc: add sponsor section in readme

internal/nocalhost-control-plane/resource/resource.go
envoy support websocket
@anurnomeru @yuyicai @xinxinh2020 
=> feat: enovy support websocket

internal/nhctl/vpn/remote/dhcp.go
=> Fix typo in dhcp.go

internal/nhctl/vpn/pkg/connect.go, internal/nhctl/vpn/remote/dhcp.go
=> Release v0.6.20

internal/nhctl/appmeta_manager/application_secret_watcher.go
https://medium.com/swlh/use-pointer-of-for-range-loop-variable-in-go-3d3481f7ffc9
=> bugfix: for-range pointer

scripts/build/control-plane/docker
=> fix: fix typo

deployments/nocalhost-envoy/envoy.yaml
=> fix: fix origin cluster grpc protocol error

internal/nhctl/syncthing/syncthingInstaller.go
=> fix: close from file

internal/nhctl/dev_dir/dev_dir_mapping.go, internal/nhctl/ui/dev.go, internal/nocalhost-api/service/cooperator/cluster_scope/cluster_role_binding_watcher.go, internal/nocalhost-dep/cm/cm_watcher.go, internal/nocalhost-dep/serviceaccount/service_account_watcher.go
=> chore: unnecessary use of fmt.Sprintf
